# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f2ec36728222e832e02b53e1c29c8f9d4e622eb3e76a783d219982f13d0c735eadc7795d4ec71afe0faa3ed91aeb66f9f52567b9dbcaec7ca5b323a91af9431

test:
  secret_key_base: 40263e12671dac2952755c2fb7da0b39b3aa113f49fb5551aaf8a073f1dce024388e9130be29e761c41547841cae06fe636edfe6d7b29a95713ace1aebad0bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
